dataset:
  mlhdf_ver: 2
  train_csvs: 
    - /path/to/train.csv
  train_set1_npy:
    - /path/to/mordred_train.npy
  train_set2_npy:
    - /path/to/egnn_train.npy

  val_csvs: 
    - /path/to/valid.csv
  val_set1_npy:
    - /path/to/mordred_val.npy
  val_set2_npy:
    - /path/to/egnn_val.npy

  test_csvs:
    - /path/to/test.csv
  test_set1_npy:
    - /path/to/mordred_test.npy
  test_set2_npy:
    - /path/to/egnn_test.npy


checkpoint:
  dir: /path/to/check_point
  prefix: prefix
  suffix: 1
  save_step: 10000
  freeze: 0

results_save_dir:
  dir: /path/to/results

train:
  batch_size: 50
  num_workers: 10
  epochs: 500
  lr: 0.001
  step_size: 10
  weight_decay: 0.0001
  lr_gamma: 0.9
  pred_suffix: null


test:
  batch_size: 10
  num_workers: 2
  pred_suffix: null

model:
  in_set1_channels: 50 
  in_set2_channels: 10
  nn_type: 2  # 1: PCN, 2: SGCNN, 3: SE-3
  out_dim: 1  # 1 or 6
  efeat: 0
  mordred: 1555
  loss_weight: 1.0e-2 # 1.0e-2 # 0 or 1.0e-2
  

